const productdetails = [
  {
    id: 1,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 2,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 3,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View |with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 4,
    img: require("./images/outdoorcamera.png"),
    name: "TP-Link Tapo C500 Outdoor Pan Camera",
    feature:
      "TP-Link Tapo C500 Outdoor Pan | 2MP 1080p Full HD Live View | 360° Visual Coverage with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 5,
    img: require("./images/sixthimage.png"),
    name: "CP PLUS 2MP Full HD Smart Camera",
    feature:
      "Action Camera 1080P 12MP Sports Camera Full HD 2.0 Inch Action Cam 30m with EF S18-55 | Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 6,
    img: require("./images/sixthimage.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 7,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 8,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 9,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 10,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 11,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 12,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 13,
    img: require("./images/outdoorcamera.png"),
    name: "TP-Link Tapo C500 Outdoor Pan Camera",
    feature:
      "TP-Link Tapo C500 Outdoor Pan | 2MP 1080p Full HD Live View | 360° Visual Coverage with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 14,
    img: require("./images/sixthimage.png"),
    name: "CP PLUS 2MP Full HD Smart Camera",
    feature:
      "Action Camera 1080P 12MP Sports Camera Full HD 2.0 Inch Action Cam 30m with EF S18-55 |Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 15,
    img: require("./images/sixthimage.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 16,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 17,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 18,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 19,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 20,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 21,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 22,
    img: require("./images/outdoorcamera.png"),
    name: "TP-Link Tapo C500 Outdoor Pan Camera",
    feature:
      "TP-Link Tapo C500 Outdoor Pan | 2MP 1080p Full HD Live View | 360° Visual Coverage with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 23,
    img: require("./images/sixthimage.png"),
    name: "CP PLUS 2MP Full HD Smart Camera",
    feature:
      "Action Camera 1080P 12MP Sports Camera Full HD 2.0 Inch Action Cam 30m with EF S18-55 | Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 24,
    img: require("./images/sixthimage.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 25,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 26,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 27,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
  {
    id: 28,
    img: require("./images/canonimgone.png"),
    name: "Canon EOS 1500D Mirrorless Camera",
    feature:
      "Canon EOS 1500D 24.1 24-70mm Lens with Additional Battery Digital SLR Camera (Black) with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "7197",
    count: 1,
  },
  {
    id: 29,
    img: require("./images/canonimgone.png"),
    name: "Nikon Z6 II Z-24 Mirrorless Camera",
    feature:
      "Nikon Z6 II Mirrorless Camera Z 24-70mm Lens with Additional Battery, Optical Zoom, Black with EF S18-55",
    minimalamout: "Pro Display XDR",
    minimalprice: "$6,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "8107",
    count: 1,
  },
  {
    id: 30,
    img: require("./images/rollercamera.png"),
    name: "MI Wireless Home Security Camera",
    feature:
      "MI Xiaomi Wireless Home Security Camera 2i 2022 Edition | Full HD Picture | 360 View | with Additional Battery",
    minimalamout: "Pro Display XDR",
    minimalprice: "$5,999",
    serviceamout: "Pro stand",
    serviceprice: "$999",
    adapter: "Vesa Mount Adapter",
    adapterprice: "$199",
    total: "Total",
    price: "9187",
    count: 1,
  },
];
export default productdetails;
